Test confirm-success

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -6,17 +6,46 @@ on:
         required: true
 
 jobs:
-  test:
+  find_tf_dirs:
     runs-on: ubuntu-latest
+    outputs:
+      tf_dirs: '[]'
     steps:
-
-      - name: Debug
+      - name: "Debug"
         run: |
           echo "github.ref_name: ${{ github.ref_name }}"
           echo "github.workflow_ref: ${{ github.workflow_ref }}"
           echo "inputs.action-version: ${{ inputs.action-version }}"
 
-      - name: "Call action"
-        uses: lindeskar/gha-test/foo-action@${{ inputs.action-version }}
-        with:
-          msg: "Hello world"
+  foreach:
+    runs-on: ubuntu-latest
+    needs: find_tf_dirs
+    strategy:
+      matrix:
+        tf_dir: ${{fromJson(needs.find_tf_dirs.outputs.tf_dirs)}}
+    steps:
+      - name: Debug
+        run: |
+          echo "tf_dir: ${{ matrix.tf_dir }}"
+          echo "github.ref_name: ${{ github.ref_name }}"
+          echo "github.workflow_ref: ${{ github.workflow_ref }}"
+          echo "inputs.action-version: ${{ inputs.action-version }}"
+
+      # - name: "Call action"
+      #   uses: lindeskar/gha-test/foo-action@${{ inputs.action-version }}
+      #   with:
+      #     arg: ${{ tojson(inputs.action-version) }}
+      #     msg: "Hello world"
+
+  confirm-success:
+    name: "Confirm success"
+    if: ${{ !cancelled() }}
+    needs:
+      - find_tf_dirs
+      - foreach
+    runs-on: ubuntu-latest
+    steps:
+      - if: ${{ failure() && fromJson(needs.find_tf_dirs.outputs.tf_dirs) != null }}
+        run: |
+          echo "At least one plan failed - check the previous job for more details"
+          exit 1
